name: Test, Format, and Lint

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  test-format-lint:
    name: Test, Format, and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3.10 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          python -m pytest

      - name: Format code
        run: ./venv/bin/ruff format --check

      - name: Lint Project
        run: 	./venv/bin/ruff check
