apiVersion: v1
kind: PersistentVolume
metadata:
  name: assets-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/assets # Replace with the desired path on the host machine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assets-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi