services:
  redis:
    image: "redis:6"
    ports:
      - "6379:6379"
    networks:
      - backend_network

  mongo:
    image: "mongo:4.4"
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.adminCommand(\"ping\")'"]
      interval: 10s
      timeout: 5s
      retries: 5

  data_pipeline:
    build:
      context: .
      dockerfile: docker/Dockerfile.data_pipeline
    volumes:
      - ./:/srv/recruiting/
    environment:
      MONGO_DB_URL: "mongodb://mongo:27017"
    networks:
      - backend_network
    depends_on:
      mongo:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ./:/srv/recruiting/
      - ./assets:/assets
    command: uvicorn --reload --reload-dir "/srv/recruiting/backend" --host 0.0.0.0 --port 8080 --log-level "debug" "backend.app:app"
    environment:
      MONGO_DB_URL: "mongodb://mongo:27017"
    ports:
      - "8080:8080"
    networks:
      - backend_network
    depends_on:
      data_pipeline:
        condition: service_completed_successfully

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    networks:
      - backend_network
    depends_on:
      backend:
        condition: service_started

volumes:
  mongo_data: {}

networks:
  backend_network: {}
