apiVersion: v1
kind: Service
metadata:
  name: data-pipeline
  labels:
    app: data-pipeline
spec:
  selector:
    app: data-pipeline
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP